version: "3.6"

services:
    app:
        build:
            context: ./app
            args:
                WWWUSER: '${WWWUSER}'
                WWWGROUP: '${WWWGROUP}'
        image: ${APP_IMG}
        ports:
            - ${APP_PORT:-9000}:9000 # debugging only
        environment:
            WWWUSER: '${WWWUSER}'
            WWWGROUP: '${WWWGROUP}'
        volumes:
            - '${PROJECT_ROOT}:/var/www/${APP_NAME}/current'
        networks:
            - fly
        depends_on:
            - mysql
            - redis
    
    nginx:
        build:
            context: ./nginx
            args:
                WWWUSER: '${WWWUSER}'
                WWWGROUP: '${WWWGROUP}'
        image: ${NGINX_IMG}
        ports:
            - ${HOST_HTTP_PORT:-80}:1180
            - ${HOST_HTTPS_PORT:-443}:11443
        volumes:
            - '${PROJECT_ROOT}:/var/www/${APP_NAME}/current'
        networks:
            - fly
        depends_on:
            - app

    mysql:
        build:
            context: ./mysql
        image: ${MYSQL_IMG}
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${HOST_DB_PORT}:3306
        volumes:
            - flymysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Asia/Shanghai
        networks:
            - fly

    redis:
        build:
            context: ./redis
            args:
              baseImg: ${BASE_IMG}
        image: ${CURRENT_REDIS_IMG}
        privileged: true
        ports:
            - ${HOST_REDIS_PORT}:6379 # debugging only
        networks:
            - fly

    echo:
        build:
            context: ./echo-server
            args:
              baseImg: ${BASE_IMG}
        image: ${CURRENT_ECHO_IMG}
        # We comment out the port because we forward the request
        # to echo by Nginx internally.
        #ports:
        #    - ${HOST_ECHO_PORT}:6001 # debugging only
        networks:
            - fly

networks:
    fly:
        driver: bridge

volumes:
    flymysql:
        driver: local
    flyredis:
        driver: local
