version: "3.6"

services:
    app:
        build:
            context: ./app
            args:
                WWWUSER: '${WWWUSER}'
                WWWGROUP: '${WWWGROUP}'
                APP_NAME: '${APP_NAME}'
        image: ${APP_IMG}
        container_name: "app-${APP_NAME}"
        environment:
            WWWUSER: '${WWWUSER}'
            WWWGROUP: '${WWWGROUP}'
            APP_NAME: '${APP_NAME}'
        volumes:
            - '${PROJECT_ROOT}:/var/www/${APP_NAME}/current'
        networks:
            - fly
        depends_on:
            - mysql
            - redis
    
    nginx:
        build:
            context: ./nginx
            args:
                WWWUSER: '${WWWUSER}'
                WWWGROUP: '${WWWGROUP}'
                APP_NAME: '${APP_NAME}'
                NGINX_CONF: '${NGINX_CONF}'
        image: ${NGINX_IMG}
        container_name: "nginx-${APP_NAME}"
        ports:
            - ${HOST_HTTP_PORT}:1180
            - ${HOST_HTTPS_PORT}:11443
        volumes:
            - '${PROJECT_ROOT}:/var/www/${APP_NAME}/current'
        networks:
            - fly
        depends_on:
            - app

    mysql:
        build:
            context: ./mysql
        image: ${MYSQL_IMG}
        container_name: "mysql-${APP_NAME}"
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${HOST_DB_PORT}:3306
        volumes:
            - ${DB_ROOT}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Asia/Shanghai
        networks:
            - fly

    redis:
        build:
            context: ./redis
        image: ${REDIS_IMG}
        container_name: "redis-${APP_NAME}"
        privileged: true
        ports:
            - ${HOST_REDIS_PORT}:6379 # debugging only
        networks:
            - fly

    echo:
        build:
            context: ./echo-server
        image: ${ECHO_IMG}
        container_name: "echo-${APP_NAME}"
        # We comment out the port because we forward the request
        # to echo by Nginx internally.
        #ports:
        #    - ${HOST_ECHO_PORT}:6001 # debugging only
        networks:
            - fly

networks:
    fly:
        driver: bridge

volumes:
    flymysql:
        driver: local
    flyredis:
        driver: local
