version: "3.6"

services:
    nginx:
        build:
            context: ./nginx
            args:
              appName: ${APP_NAME}
              appRootDir: ${APP_ROOT}
              baseImg: ${BASE_IMG}
        image: ${CURRENT_NGINX_IMG}
        ports:
            - ${HOST_HTTP_PORT}:80
            - ${HOST_HTTPS_PORT}:443
        volumes:
            - ${HOST_ROOT}:${CONTAINER_ROOT}
        networks:
            - bx-net

    mysql:
        build:
            context: ./mysql
        image: ${CURRENT_DB_IMG}
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${HOST_DB_PORT}:3306
        volumes:
            - ${HOST_DB_ROOT}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Asia/Shanghai
        networks:
            - bx-net

    redis:
        build:
            context: ./redis
        image: ${CURRENT_REDIS_IMG}
        privileged: true
        ports:
            - ${HOST_REDIS_PORT}:6379 # debugging only
        networks:
            - bx-net

    echo:
        build:
            context: ./echo-server
        image: ${CURRENT_ECHO_IMG}
        # We comment out the port because we forward the request
        # to echo by Nginx internally.
        #ports:
        #    - ${HOST_ECHO_PORT}:6001 # debugging only
        networks:
            - bx-net

networks:
    bx-net:
        driver: bridge
